### ISSUE TITLE
How can running windowCounts on two files together give more regions than the sum of individual runs?

### ISSUE THREAD

**Issue by endrebak** [LTLA/archive-csaw#3]
In the code below I run `windowCounts` on two files, first individually, then together.

```
data <- windowCounts(file1, ext=110, width=10, param=param)
data1 <- windowCounts(file2, ext=110, width=10, param=param)
data2 <- windowCounts(c(file1, file2), ext=110, width=10, param=param)
```

The following are the (to me counterintuitive) results I get:

```
> rowRanges(data); rowRanges(data1)
GRanges object with 4942 ranges and 0 metadata columns:
...
GRanges object with 5438 ranges and 0 metadata columns:
...
> rowRanges(data2)
GRanges object with 12738 ranges and 0 metadata columns:
...
```

I could understand it if the last windowCounts gave a number of regions below or equal to 4942 + 5438, but not getting more regions! Why does this happen (perhaps something to include in the manual/docs)?

Bonus q: is there a way to make csaw include every region, even though the expression is low there? (If all rowRanges had the same number of regions, merging the data would be much easier.)

**Comment by LTLA** [comment]
Because `windowCounts` filters based on the `filter` argument. By default, this is 10, so a window with a sum of counts across both files at or above 10 will be included in `data2`, even if the counts in each file are below 10 (and thus, not included in `data` or `data1`). This results in more regions in `data2`, as you've observed. If you want regions to be identical, you should set `filter=0`, which will do no filtering at all.

For future reference, unless you're using BioC-devel-specific functions, this type of question should be posted to the Bioconductor support site at http://support.bioconductor.org.

**Comment by endrebak** [comment]
Thanks.
